# Generated by Django 6.1 on 2026-09-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0003_projecto_mentor'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoMentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('modalidade', models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], default='ONLINE', max_length=20)),
                ('link_meet', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONCLUIDA', 'Concluída'), ('REAGENDADA', 'Reagendada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='mentor.mentor')),
                ('projecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_mentoria', to='estudante.projecto')),
            ],
        ),
    ]
