# Generated by Django 6.1 on 2026-09-09 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_sessaomentoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaMentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField()),
                ('decisoes', models.TextField()),
                ('proximos_passos', models.TextField()),
                ('estado_projecto', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSA', 'Em pausa'), ('RISCO', 'Em risco'), ('CONCLUIDO', 'Concluído')], default='ACTIVO', max_length=20)),
                ('estado_ata', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDA', 'Submetida')], default='RASCUNHO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('submetido_em', models.DateTimeField(blank=True, null=True)),
                ('sessao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ata', to='mentor.sessaomentoria')),
            ],
        ),
    ]
