# Generated by Django 6.1 on 2026-09-12 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudante', '0004_projecto_area_atuacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_investidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestacaoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(choices=[('PARCERIA', 'Parceria'), ('INVESTIMENTO', 'Investimento'), ('PATROCINIO', 'Patrocínio')], max_length=20)),
                ('mensagem', models.TextField()),
                ('contacto_direto', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('EM_ANALISE', 'Em análise'), ('RESPONDIDA', 'Respondida')], default='ENVIADA', max_length=20)),
                ('resposta', models.TextField(blank=True)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestacoes', to='investidor.investidor')),
                ('projecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestacoes_interesse', to='estudante.projecto')),
            ],
        ),
    ]
