# Generated by Django 6.1 on 2026-09-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investidor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestacaointeresse',
            name='decisao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITE', 'Aceite'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=20),
        ),
    ]
