# Generated by Django 6.1 on 2026-09-02 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('faculdade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='estudante.faculdade')),
            ],
            options={
                'unique_together': {('faculdade', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='PerfilAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('numero_estudante', models.CharField(max_length=30, unique=True)),
                ('ano_academico', models.CharField(choices=[('1', '1.º Ano'), ('2', '2.º Ano'), ('3', '3.º Ano'), ('4', '4.º Ano'), ('5', '5.º Ano'), ('LICENCIADO', 'Recém-licenciado')], max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('descricao_interesse', models.TextField(blank=True)),
                ('comprovativo_academico', models.FileField(blank=True, null=True, upload_to='estudante/comprovativos/')),
                ('estado_validacao', models.CharField(choices=[('INCOMPLETO', 'Incompleto'), ('PENDENTE', 'Pendente'), ('VALIDADO', 'Validado'), ('REJEITADO', 'Rejeitado')], default='INCOMPLETO', max_length=20)),
                ('observacao_validacao', models.TextField(blank=True)),
                ('submetido_em', models.DateTimeField(blank=True, null=True)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudantes', to='estudante.curso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_academico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
