# Generated by Django 6.1 on 2026-09-07 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo_executivo', models.TextField()),
                ('problema', models.TextField()),
                ('solucao', models.TextField()),
                ('modelo_negocio', models.TextField()),
                ('equipa', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='estudante/projectos/')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente de Avaliação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('EM_INCUBACAO', 'Em Incubação'), ('PUBLICADO', 'Publicado')], default='PENDENTE', max_length=20)),
                ('parecer_avaliacao', models.TextField(blank=True)),
                ('submetido_em', models.DateTimeField(auto_now_add=True)),
                ('avaliado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectos', to='estudante.perfilacademico')),
            ],
        ),
    ]
