# Generated by Django 6.1 on 2026-09-09 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0002_projecto'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecto',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectos', to='mentor.mentor'),
        ),
    ]
