# Generated by Django 6.1 on 2026-09-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0003_projecto_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecto',
            name='area_atuacao',
            field=models.CharField(blank=True, choices=[('FINTECH', 'Fintech'), ('AGROTECH', 'Agrotech'), ('EDUTECH', 'Edutech'), ('HEALTHTECH', 'Healthtech'), ('PROPTECH_CONSTRUTECH', 'Proptech / Construtech'), ('RETAILTECH_LOGTECH', 'Retailtech / Logtech'), ('GREENTECH_CLEANTECH', 'Greentech / Cleantech'), ('GOVTECH', 'Govtech')], max_length=30),
        ),
    ]
