# Generated by Django 6.1 on 2026-09-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0004_projecto_area_atuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecto',
            name='captacao_encerrada',
            field=models.BooleanField(default=False),
        ),
    ]
